trigger:
  branches:
    include:
    - main

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

resources:
  repositories:
  # Repo: 1ESPipelineTemplates/1ESPipelineTemplates
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - name: BuildScriptArgs
    value: ''
- ${{ if ne(variables['System.TeamProject'], 'public') }}:
  - name: BuildScriptArgs
    value: '/p:BuildNumber=$(Build.BuildId)'


extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: NetCore1ESPool-Svc-Internal
      image: 1es-windows-2019-pt
      os: windows
    stages:
    - stage: build
      displayName: Build
      jobs:
      - template: /eng/templates/default-build.yml@self